version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.4
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: install dependencies
          command: npm install
